version: "3"

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postresql
      POSTGRES_PASSWORD: postresql
      POSTGRES_DB: online-judge
